import mongoose, { Schema, Document } from 'mongoose';
import { QuestionType, Answer } from '../types';
import type { EchoScreeningPayload } from '../utils/shkEchoScreening';

export interface IResponse extends Document {
  userId: mongoose.Types.ObjectId;
  /** Personal ID generated by mobile app (e.g. HZB202503A1B2) */
  pid?: string;
  /** Birth date (YYYY-MM-DD) – used for consent PDF password and reporting */
  birthDate?: string;
  /** Patient gender code: male | female | diverse | other | prefer_not_to_say */
  gender?: string;
  /** SHK flagged pathological / control-required finding — orange tag on web + nachverfolgung email */
  pathologicalFindingReport?: boolean;
  answers: Answer[];
  signatureBase64?: string;
  draft: boolean;
  completedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  intervieweeName?: string;
  intervieweeEmail?: string;
  intervieweePhone?: string;
  intervieweeAddress?: string;
  workflowStatus:
    | 'patient_in_progress'
    | 'patient_completed'
    | 'pending_shk_followup'
    | 'shk_in_progress'
    | 'closed';
  /** True when the response was finalized from patient-bounded app mode (awaits SHK follow-up + emails). */
  patientBoundedSubmit?: boolean;
  /** Consent PDF (base64) queued until SHK completes follow-up (patient-bounded flow). */
  consentPdfBase64Deferred?: string;
  shkFollowUp?: {
    /** @deprecated Legacy checklist; new flow uses echoScreening */
    answers?: Record<string, boolean>;
    echoScreening?: EchoScreeningPayload;
    completedAt?: Date;
  };
  lockedBy?: mongoose.Types.ObjectId;
  lockedAt?: Date;
  closedAt?: Date;
  changeLog: Array<{
    changedBy: mongoose.Types.ObjectId;
    changedAt: Date;
    source: 'PATIENT' | 'SHK' | 'SYSTEM';
    reason?: string;
    changes: Array<{
      field: string;
      previousValue: string;
      nextValue: string;
    }>;
  }>;
}

const AnswerSchema = new Schema({
  questionId: { type: String, required: true },
  type: {
    type: String,
    enum: ['SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TEXT', 'NUMBER', 'RATING', 'DATE', 'IMAGE_UPLOAD', 'FILE_UPLOAD', 'GEOLOCATION', 'SIGNATURE'],
    required: true,
  },
  value: {
    type: Schema.Types.Mixed,
    // Note: We validate value presence in the route handler for better error messages
    // Schema-level validation is complex due to conditional requirements for file types
  },
  imageUri: String,
  fileUri: String,
  signatureBase64: String,
}, { _id: false });

const ResponseSchema = new Schema<IResponse>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    pid: {
      type: String,
      trim: true,
    },
    birthDate: {
      type: String,
      trim: true,
    },
    gender: {
      type: String,
      trim: true,
    },
    pathologicalFindingReport: {
      type: Boolean,
      default: false,
    },
    answers: {
      type: [AnswerSchema],
      default: [],
    },
    signatureBase64: {
      type: String,
    },
    draft: {
      type: Boolean,
      default: true,
    },
    completedAt: {
      type: Date,
    },
    intervieweeName: {
      type: String,
      trim: true,
    },
    intervieweeEmail: {
      type: String,
      trim: true,
      lowercase: true,
      validate: {
        validator: function(v: string) {
          // Allow empty/undefined (field is optional)
          if (!v || v === '') return true;
          // Validate email format if provided
          const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
          return emailRegex.test(v);
        },
        message: 'Please provide a valid email address',
      },
    },
    intervieweePhone: {
      type: String,
      trim: true,
    },
    intervieweeAddress: {
      type: String,
      trim: true,
    },
    workflowStatus: {
      type: String,
      enum: [
        'patient_in_progress',
        'patient_completed',
        'pending_shk_followup',
        'shk_in_progress',
        'closed',
      ],
      default: 'patient_in_progress',
    },
    patientBoundedSubmit: {
      type: Boolean,
      default: false,
    },
    consentPdfBase64Deferred: {
      type: String,
    },
    shkFollowUp: {
      type: new Schema(
        {
          answers: { type: Schema.Types.Mixed, default: {} },
          echoScreening: { type: Schema.Types.Mixed },
          completedAt: { type: Date },
        },
        { _id: false }
      ),
    },
    lockedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
    },
    lockedAt: {
      type: Date,
    },
    closedAt: {
      type: Date,
    },
    changeLog: {
      type: [
        new Schema(
          {
            changedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
            changedAt: { type: Date, required: true },
            source: { type: String, enum: ['PATIENT', 'SHK', 'SYSTEM'], required: true },
            reason: { type: String },
            changes: {
              type: [
                new Schema(
                  {
                    field: { type: String, required: true },
                    previousValue: { type: String, default: '' },
                    nextValue: { type: String, default: '' },
                  },
                  { _id: false }
                ),
              ],
              default: [],
            },
          },
          { _id: false }
        ),
      ],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

// Indexes
ResponseSchema.index({ userId: 1 });
ResponseSchema.index({ draft: 1 });
ResponseSchema.index({ completedAt: -1 });
ResponseSchema.index({ createdAt: -1 });
ResponseSchema.index({ intervieweeName: 1 });
ResponseSchema.index({ intervieweeEmail: 1 });
ResponseSchema.index({ pid: 1 });
ResponseSchema.index({ workflowStatus: 1 });
ResponseSchema.index({ lockedBy: 1 });

export const Response = mongoose.model<IResponse>('Response', ResponseSchema);

